language: node_js
node_js:
  - 'stable'
  - '9'
  - '8'
  - '7'
  - '6'
  - '6.0.0'
  - '5'
  - '5.0.0'
  - '4'
  - '4.4.0'
  - '4.0.0'
  - '0.12'
  - '0.12.0'
  - '0.10'
notifications:
  email: false
