language: node_js
node_js:
  - 'stable'
  - '9'
  - '8'
  - '7'
  - '6'
  - '6.0.0'
  - '5'
  - '5.0.0'
  - '4'
  - '4.4.0'
  - '4.0.0'
  - '0.12'
  - '0.12.0'
  - '0.10'
  - '0.8'
  - '0.8.6'
matrix:
  include:
    - node_js: 'stable'
      script: npm install browserify && npm run browserify-test
before_install:
  - 'case "${TRAVIS_NODE_VERSION}" in 0.*) export NPM_CONFIG_STRICT_SSL=false ;; esac'
  - 'nvm install-latest-npm'
notifications:
  email: false
