language: node_js
node_js:
  - 'stable'
  - '9'
  - '8'
  - '7'
  - '6'
  - '6.0.0'
  - '5'
  - '5.0.0'
  - '4'
  - '4.4.0'
  - '4.0.0'
  - '0.12'
  - '0.12.0'
  - '0.10'
  - '0.10.0'
  - '0.8'
before_install:
  - 'case "${TRAVIS_NODE_VERSION}" in 0.*) npm config set strict-ssl false;; esac'
  - 'nvm install-latest-npm'
  - 'case "${TRAVIS_NODE_VERSION}" in 0.*) npm config delete strict-ssl;; esac'
notifications:
  email: false
